### ISSUE TITLE
What's the purpose of the custom roles?

### ISSUE THREAD

**Issue by leonelgalan** [smashingboxes/tape#31]
According to the README (and empty YAML files in my projects) this custom roles exist?
* ~~before_database~~
* ~~before_general~~
* ~~before_web~~
* ~~before_ruby~~
* ~~before_app_server~~
* ~~before_deploy~~
* after_deploy

(**EDIT**: Most of them are gone after last update)

What's the purpose of these? I guess I'm looking for examples on what would someone do on each of these?

Today, I'll make this files optional, so they are created on the repo only if needed. PR coming soon.

**Comment by leonelgalan** [comment]
## Not as easy as I thought:

http://docs.ansible.com/playbooks_conditionals.html#applying-when-to-roles-and-includes
> "All the tasks get evaluated, but the conditional is applied to each and every task"

```yml
- local_action: stat path={{local_dir}}/roles/after_deploy.yml
  register: after_deploy
- include: "{{local_dir}}/roles/after_deploy.yml"
  when: after_deploy.stat.exists
```

Still fails with `ERROR: file could not read: /project_path/roles/after_deploy.yml` because the file is loaded, `when` will just apply that condition to all tasks loaded.
